lexik_jwt_authentication:
    secret_key:       '%kernel.project_dir%/config/jwt/private.pem' # required for token creation
    public_key:       '%kernel.project_dir%/config/jwt/public.pem'  # required for token verification
    token_ttl:        3600
    pass_phrase: '%env(JWT_PASSPHRASE)%'
